name: CI - E2E without Docker

on:
  push:
  pull_request:

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: sleeplab
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      DB_DSN: postgresql://postgres:postgres@localhost:5432/sleeplab

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r etl/requirements.txt

      - name: Init DB (DDL + seed + views)
        run: python scripts/db_init.py

      - name: Run tests
        run: pytest -v

      - name: Run ETL demo
        run: python etl/app/etl_demo.py
